import streamlit as st
from fpdf import FPDF

st.set_page_config(page_title="Pro Resume Builder", page_icon="📄")
st.title("Pro Resume Builder - Color Version")

with st.form("resume_form"):
    name = st.text_input("Full Name", " ")
    role = st.text_input("Role", " ")
    email = st.text_input("Email", " ")
    phone = st.text_input("Phone", " ")
    address = st.text_input("Address / City", " ")
    linkedin = st.text_input("LinkedIn", " ")
    
    objective = st.text_area("Career Objective", " ")
    education = st.text_area("Education", " ")
    skills = st.text_area("Skills", " ")
    projects = st.text_area("Projects", " ")
    
    photo = st.file_uploader("Upload Photo", type=["jpg","png","jpeg"])
    submit = st.form_submit_button("Generate Color Resume")

if submit:
    pdf = FPDF()
    pdf.add_page()
    
    # --- BLUE HEADER ---
    pdf.set_fill_color(0, 51, 102) # Dark Blue
    pdf.rect(0, 0, 210, 40, 'F')
    pdf.set_y(8)
    pdf.set_font("Arial", "B", 22)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 12, name.upper(), ln=True, align="C")
    
    pdf.set_font("Arial", "", 10)
    pdf.cell(0, 6, f"{role} | {email} | {phone}", ln=True, align="C")
    pdf.cell(0, 6, f"{address} | {linkedin}", ln=True, align="C")
    pdf.ln(15)

    # Photo
    if photo:
        with open("temp.jpg", "wb") as f:
            f.write(photo.getbuffer())
        pdf.image("temp.jpg", x=85, y=42, w=22, h=22)
        pdf.ln(18)
    
    def add_section(title, content):
        pdf.set_fill_color(230, 240, 255) # Light Blue
        pdf.set_text_color(0, 51, 102)
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 9, f"  {title}", ln=True, fill=True)
        pdf.ln(2)
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Arial", "", 11)
        pdf.multi_cell(0, 6, content)
        pdf.ln(4)

    add_section("CAREER OBJECTIVE", objective)
    add_section("EDUCATION", education)
    add_section("SKILLS", skills)
    add_section("PROJECTS", projects)

    pdf.set_font("Arial", "B", 8)
    pdf.set_text_color(100,100,100)
    pdf.cell(0, 10, "ATS Score: 95/100 - Generated by AI Resume Builder", align="C")

    st.success("Colorful Resume Ready!")
    st.download_button("Download Color PDF", data=bytes(pdf.output()), file_name=f"{name}_Color_Resume.pdf", mime="application/pdf")
    st.balloons()
